In [3]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from datetime import datetime, date, time
from dateutil import parser

In [4]:
pd.read_csv(r'national_family_health_survey.csv')

,Unnamed: 0,District Names,State/UT,Number of Households surveyed,Number of Women age 15-49 years interviewed,Number of Men age 15-54 years interviewed,Female population age 6 years and above who ever attended school (%),Population below age 15 years (%),"Sex ratio of the total population (females per 1,000 males)","Sex ratio at birth for children born in the last five years (females per 1,000 males)",...,Men age 15 years and above wih Mildly elevated blood pressure (Systolic 140-159 mm of Hg and/or Diastolic 90-99 mm of Hg) (%),Men age 15 years and above wih Moderately or severely elevated blood pressure (Systolic ≥160 mm of Hg and/or Diastolic ≥100 mm of Hg) (%),Men age 15 years and above wih Elevated blood pressure (Systolic ≥140 mm of Hg and/or Diastolic ≥90 mm of Hg) or taking medicine to control blood pressure (%),Women (age 30-49 years) Ever undergone a screening test for cervical cancer (%),Women (age 30-49 years) Ever undergone a breast examination for breast cancer (%),Women (age 30-49 years) Ever undergone an oral cavity examination for oral cancer (%),Women age 15 years and above who use any kind of tobacco (%),Men age 15 years and above who use any kind of tobacco (%),Women age 15 years and above who consume alcohol (%),Men age 15 years and above who consume alcohol (%)
0,0,Nicobars,Andaman & Nicobar Islands,882,764,125,78.0,23.0,973,927,...,32.9,11.1,47.0,13.4,13.2,5.4,63.5,76.8,29.6,64.5
1,1,North & Middle Andaman,Andaman & Nicobar Islands,874,789,108,82.7,19.8,950,844,...,22.6,6.0,32.2,1.7,0.3,15.8,46.8,70.5,5.1,45.3
2,2,South Andaman,Andaman & Nicobar Islands,868,844,134,84.7,21.0,967,935,...,17.9,6.1,26.9,1.3,0.7,8.0,19.6,50.8,1.7,32.8
3,3,Srikakulam,Andhra Pradesh,874,780,100,60.0,20.7,1140,1163,...,14.4,5.5,22.9,1.0,0.2,3.8,7.1,21.3,0.6,28.3
4,4,Vizianagaram,Andhra Pradesh,902,853,134,56.0,20.6,1114,898,...,14.8,6.4,25.1,4.9,0.6,7.3,11.4,21.5,0.8,32.3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
701,701,Kolkata,West Bengal,879,921,138,87.2,16.0,954,809,...,15.0,5.1,23.8,0.0,0.0,0.0,6.0,42.4,1.0,22.2
702,702,South Twenty Four Pargana,West Bengal,917,1089,148,80.9,25.5,1055,1099,...,13.0,4.3,19.1,0.0,0.0,0.2,6.3,49.8,0.4,16.5
703,703,Paschim Medinipur,West Bengal,910,1002,137,72.1,23.4,1089,1005,...,10.7,4.3,19.0,0.0,0.0,0.0,18.8,50.5,1.5,20.8
704,704,Purba Medinipur,West Bengal,873,957,131,83.0,23.9,1031,777,...,11.9,4.4,21.3,0.0,0.2,0.5,12.9,40.1,2.0,14.8
705,705,Paschim Barddhaman,West Bengal,912,1190,184,74.8,22.3,977,787,...,14.5,3.7,20.7,0.7,1.3,0.4,11.8,40.2,0.8,14.6