# Data Science -  Business Challenge
# Government Agency - Analysis of Consumer complaint from Financial Institution

In [13]:
import numpy as np

In [27]:
import pandas as pd
import qgrid


# Importing the csv file that houses the dataset
# see csv files in the folder

In [28]:
consumer = pd.read_csv(r'C:\Users\godwi\OneDrive\Documents\Data Science\GitHub\Python-Pandas\Government Agency\P9-ConsumerComplaints.csv',\
low_memory=False)

In [29]:
consumer.sample(10) # selecting 10 rows to validate data

,Date Received,Product Name,Sub Product,Issue,Sub Issue,Consumer Complaint Narrative,Company Public Response,Company,State Name,Zip Code,Tags,Consumer Consent Provided,Submitted via,Date Sent to Company,Company Response to Consumer,Timely Response,Consumer Disputed,Complaint ID
20764,3/31/2014,Debt collection,I do not know,Communication tactics,Frequent or repeated calls,NaN,NaN,"Dynamic Recovery Solutions, LLC",FL,33635,NaN,NaN,Phone,4/16/2014,Closed with explanation,Yes,No,785426
59628,3/6/2015,Credit reporting,NaN,Incorrect information on credit report,Personal information,NaN,NaN,Experian,TX,78572,NaN,NaN,Web,3/12/2015,Closed with explanation,Yes,No,1270434
51020,1/10/2015,Debt collection,Credit card,Taking/threatening an illegal action,Threatened to sue on too old debt,NaN,NaN,Resurgent Capital Services L.P.,MA,2169,NaN,NaN,Web,1/10/2015,Closed with explanation,Yes,No,1189242
60099,4/9/2015,Credit reporting,NaN,Incorrect information on credit report,Information is not mine,NaN,Company chooses not to provide a public response,Experian,WA,98501,NaN,Consent not provided,Web,4/9/2015,Closed with non-monetary relief,Yes,No,1323728
39818,9/18/2014,Mortgage,Other mortgage,"Loan servicing, payments, escrow account",NaN,NaN,NaN,EverBank,FL,32812,NaN,NaN,Referral,9/24/2014,Closed with explanation,Yes,Yes,1035565
28431,5/19/2014,Mortgage,Other mortgage,"Loan modification,collection,foreclosure",NaN,NaN,NaN,Nationstar Mortgage,FL,34477,NaN,NaN,Web,5/19/2014,Closed with explanation,Yes,No,858761
40007,9/9/2014,Bank account or service,(CD) Certificate of deposit,Deposits and withdrawals,NaN,NaN,NaN,JPMorgan Chase & Co.,FL,34711,NaN,NaN,Web,9/9/2014,Closed with explanation,Yes,No,1021458
25450,5/4/2014,Credit reporting,NaN,Incorrect information on credit report,Information is not mine,NaN,NaN,Equifax,NY,10452,NaN,NaN,Web,5/4/2014,Closed with explanation,Yes,Yes,837074
14422,1/31/2014,Bank account or service,Other bank product/service,Using a debit or ATM card,NaN,NaN,NaN,Bank of America,VA,22203,NaN,NaN,Web,1/31/2014,Closed with explanation,Yes,No,696425
42816,9/29/2014,Mortgage,Conventional fixed mortgage,"Loan modification,collection,foreclosure",NaN,NaN,NaN,Wells Fargo & Company,AL,36849,NaN,NaN,Web,9/29/2014,Closed with explanation,Yes,No,1048558

# Understanding the data, type, shape

In [17]:
consumer.info(verbose= False)
# dataset is made up of integers, object types

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 65499 entries, 0 to 65498
Columns: 18 entries, Date Received to Complaint ID
dtypes: int64(1), object(17)
memory usage: 9.0+ MB

In [18]:
consumer.shape   
# data has 65499 rows and 18 columns

(65499, 18)

# The Business -  Question 1 : 
# How many complaint were received and sent on same day

In [19]:
# Question 1 : # how many complaint were received and sent on same day
received_com_sameday = consumer.loc[:, ['Complaint ID','Date Received','Date Sent to Company']]

In [20]:
received_com_sameday[received_com_sameday['Date Sent to Company'] ==\
                     received_com_sameday['Date Received']].count()
# 2,8737 complaints were received and sent on same day

Complaint ID            28737
Date Received           28737
Date Sent to Company    28737
dtype: int64

# The Business -  Question 2 : 
# Extract the complaints received in the state of New York

In [21]:
# Quetion 2    : # Extract the complaints received in the state of New York
consumer.loc[:, ['Complaint ID','State Name']].head()

   Complaint ID State Name
0        468882         VA
1        468889         CA
2        468879         NY
3        468949         GA
4        475823         CT

In [22]:
# Qestion 2    : # Extract the complaints received in the state of New York
# step 1
complaints_NY =consumer.loc[:,['Complaint ID', 'Company','State Name','Date Received','Date Sent to Company'] ]

In [23]:
# Qestion 2    : # Extract the complaints received in the state of New York
# step 2
complaints_NY[complaints_NY['State Name'] == 'NY'].head(5)

,Complaint ID,Company,State Name,Date Received,Date Sent to Company
2,468879,Santander Bank US,NY,7/29/2013,7/31/2013
15,469057,JPMorgan Chase & Co.,NY,7/29/2013,7/31/2013
17,469070,JPMorgan Chase & Co.,NY,7/29/2013,7/30/2013
23,480173,Wells Fargo & Company,NY,7/29/2013,7/31/2013
24,469360,Ocwen,NY,7/29/2013,7/30/2013

# The Business -  Question 3 : 
# Extract the complaints received in the state of New York and California

In [24]:
# Qestion 3    : # Extract the complaints received in the state of New York amnd California
# step 2
complaints_NY[(complaints_NY['State Name'] == 'NY') | (complaints_NY['State Name'] == 'CA')]

,Complaint ID,Company,State Name,Date Received,Date Sent to Company
1,468889,Wells Fargo & Company,CA,7/29/2013,7/31/2013
2,468879,Santander Bank US,NY,7/29/2013,7/31/2013
11,469284,JPMorgan Chase & Co.,CA,7/29/2013,7/30/2013
12,480488,Citibank,CA,7/29/2013,7/31/2013
15,469057,JPMorgan Chase & Co.,NY,7/29/2013,7/31/2013
...,...,...,...,...,...
65483,1362371,Wells Fargo & Company,CA,5/6/2015,5/7/2015
65490,1385061,"PayPal Holdings, Inc.",CA,5/20/2015,5/20/2015
65492,1363172,Ocwen,CA,5/6/2015,5/7/2015
65495,1364367,Bank of America,CA,5/6/2015,5/7/2015
65497,1363039,"Afni, Inc.",CA,5/6/2015,5/7/2015

# The Business -  Question 4 : 
# Extract the rows with the word 'credit in product field'

In [25]:
# Question 4  Extract the rows with the word 'credit in product field'
consumer[consumer['Product Name'].str.contains('Credit',case= False)].head()

,Date Received,Product Name,Sub Product,Issue,Sub Issue,Consumer Complaint Narrative,Company Public Response,Company,State Name,Zip Code,Tags,Consumer Consent Provided,Submitted via,Date Sent to Company,Company Response to Consumer,Timely Response,Consumer Disputed,Complaint ID
8,7/29/2013,Credit card,NaN,Billing statement,NaN,NaN,NaN,Citibank,OH,45247,NaN,NaN,Referral,7/30/2013,Closed with explanation,Yes,Yes,469026
19,7/29/2013,Credit card,NaN,APR or interest rate,NaN,NaN,NaN,Synchrony Financial,WA,98548,NaN,NaN,Web,7/29/2013,Closed with monetary relief,Yes,No,469131
20,7/29/2013,Credit reporting,NaN,Credit monitoring or identity protection,Problem cancelling or closing account,NaN,NaN,Experian,CA,90034,NaN,NaN,Web,7/29/2013,Closed with monetary relief,Yes,No,474204
28,7/29/2013,Credit reporting,NaN,Incorrect information on credit report,Public record,NaN,NaN,Equifax,CA,91605,NaN,NaN,Web,7/29/2013,Closed with non-monetary relief,Yes,No,469201
37,7/29/2013,Credit card,NaN,Delinquent account,NaN,NaN,NaN,Amex,TX,78232,NaN,NaN,Web,7/29/2013,Closed with monetary relief,Yes,No,479990

# The Business -  Question 5 : 
# Extract the rows with the word 'late in issues field'

In [26]:
consumer[consumer['Issue'].str.contains('Late',case= False)].head()

,Date Received,Product Name,Sub Product,Issue,Sub Issue,Consumer Complaint Narrative,Company Public Response,Company,State Name,Zip Code,Tags,Consumer Consent Provided,Submitted via,Date Sent to Company,Company Response to Consumer,Timely Response,Consumer Disputed,Complaint ID
199,7/31/2013,Credit card,NaN,Late fee,NaN,NaN,NaN,JPMorgan Chase & Co.,IL,60201,NaN,NaN,Web,7/31/2013,Closed with monetary relief,Yes,No,471204
400,7/23/2013,Credit card,NaN,Late fee,NaN,NaN,NaN,Capital One,AR,72015,NaN,NaN,Web,7/23/2013,Closed with monetary relief,Yes,No,463829
477,8/7/2013,Credit card,NaN,Late fee,NaN,NaN,NaN,Citibank,CA,94523,NaN,NaN,Web,8/7/2013,Closed with monetary relief,Yes,No,488956
1010,8/14/2013,Credit card,NaN,Late fee,NaN,NaN,NaN,Citibank,TX,75024,NaN,NaN,Web,8/14/2013,Closed with monetary relief,Yes,No,492046
1313,8/14/2013,Credit card,NaN,Late fee,NaN,NaN,NaN,Bank of America,NY,10024,NaN,NaN,Web,8/20/2013,Closed with monetary relief,Yes,No,492446